name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: ./test-playwright || npm ci
    - name: Install Playwright Browsers
      working-directory: ./test-playwright
      run: ./test-playwright || npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./test-playwright
      run: ./test-playwright || npx playwright test
    - uses: actions/upload-artifact@v3
      run: ./test-playwright
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
